### PR TITLE
Fix pagination when paginate_link points to a directory

### LINKED ISSUE #254: Pagination does not work when pagine_link points to a directory
When specifiing a directory (end with "/") as permalink, Pretzel automatically creates the directory and the index.html file inside.
When specifying a directory for paginate_link an IOException is thrown.

### PR DESCRIPTION
**Pull request by kodfodrasz**
permalink can point to a directory, and Pretzel knows it must create an index.html in that directory.
This patch add support for this behavior when pagination is used.
Modified custom pagination link tests to test this case.

fixes #254

### CODE REVIEW

**Comment by laedit** [comment]
Sorry for the silence, I was out of town for a few weeks.
Thanks a lot for your PR, I haven't the time to check all pagination :smiley: 
Could you just merge your PR with the updated master?
Thanks in advance.

**Comment by kodfodrasz** [comment]
Sure. Probably I'll do it in the weekend.

**Comment by kodfodrasz** [comment]
Updated branch with upstream changes. (btw is any notification generated by updating the branch in the PR?)

**Comment by laedit** [comment]
Thanks!
I didn't receive mail for each commits if that's what your mean.

**Comment by kodfodrasz** [comment]
Yes that is what I meant. Then my comments (except for this one) weren't purely useless redundant spam. :smile:

**Pull request merged**
