### PR TITLE
Rework Razor site template to be more "razor style"...

### PR DESCRIPTION
**Pull request by kodfodrasz**
# Rework Razor site template to be more "razor style", and a better example to newcomers
- templates use Razor Layout property for master pages, and @section
- Razor code is from .md files is moved to views. Content is for content only!
- Examples for fetching options from the configuration
- repeating fields in feeds moved to variables
- tests updated to test for new file layout
- tested and works as expected (naturally!)
# TODO
- The wiki style example layout is not updated yet. It will be pushed to this branch soon.

### CODE REVIEW

**Comment by laedit** [comment]
I am not sure this was wanted: in Pretzel Razor is used only as template language, like Liquid and not to define configuration and other things. The original goal was to stay as close as possible to Jekyll.
And I'm afraid that if the configuration is not in YAML that could raise some issues.

@shiftkey , @JakeGinnivan what is your opinion on this?

**Comment by kodfodrasz** [comment]
If not wanted, then reject it. This is just a pull *request* after all! ;)

About the changes: 
I have kept the config in YAML in `_config` and the front matter, even moved some repeated wired-in data there (in the RSS and Atom templates. I have only made the razor templates (with the very same effects) to look more like a Razor template used in traditional ASP.Net or Nancy.

What I have changed is that I have moved the razor-heavy stuff to layouts from markdown files.

I know these are cosmetic changes only, and are based on personal preference/style, but for me it was some struggle to clear parts of this, while doing my site, as I'm not a big Razor magician, and thought it might serve other well. 

Also note: even if you'd opt to accept this proposal, first just tell me in a comment, and then I'll rework the wiki style pages as well.

**Comment by laedit** [comment]
Sorry if my message was harsh, my english is clumsy.

Thanks for the explanation, that help :smiley: 

I will test it probably before the end of the week and let you know the result.

**Comment by laedit** [comment]
I haven't realized that only the layouts are full razor and the posts and pages keep the yaml config.
So after some tests I can say that it's an excellent idea and please, make the wiki like this one :smiley:

**Comment by brgrz** [comment]
This makes lots of sense. Is this getting merged any time soon?

**Comment by laedit** [comment]
As soon as it is complete: the wiki is still awaited.

**Comment by laedit** [comment]
@kodfodrasz do you intend to finish this PR? If yes can you rebase it again the master?

**Comment by kodfodrasz** [comment]
Hi!

I intend to finish this, just never get to do it. :(

I'll rebase it of course.

**Comment by laedit** [comment]
All right, thanks! :smiley:

**Comment by kodfodrasz** [comment]
Sorry, I have no capacity to finish this.

**Comment by laedit** [comment]
No problem, I understand, thanks for participating already! 😄

**Pull request closed without merging**
