### PR TITLE
Accessible configuration

### LINKED ISSUE #285: Accessing config in an ILightweightMarkupEngine implementation
I have written a plugin implementing `ILightweightMarkupEngine`. I'd like to make it configurable with options set in `_config.yml`. However, I don't see a way to access the configuration.

I ask to either add the `SiteContext` (or `SiteContext.Config`) to the container so it gets injectable, or add `SiteContext` as an additional parameter to `ILightweightMarkupEngine.Convert()`

### PR DESCRIPTION
**Pull request by laedit**
Fix #285
Configuration is now accessible through MEF as IConfiguration.

### CODE REVIEW

**Comment by laedit** [comment]
@thoemmi I hadn't the time to test it in a real plugin but this should work.
Could you tell me if it's ok for you?

**Comment by thoemmi** [comment]
@laedit I tried it in my plugin, it works great! :+1: :shipit:

**Comment by thoemmi** [comment]
Well, my other plugin crashes when I don't re-compile it. It uses this code
```
if (!context.Config.TryGetValue("redirect_generate_aspx", out generateAspx)) {
    return false;
}
```
which will throw `System.MissingMethodException`:
> Additional information: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Object> Pretzel.Logic.Templating.Context.SiteContext.get_Config()'.

I don't know if this is a showstopper, because introducing `IConfiguration` may break existing plugins.

**Comment by laedit** [comment]
I know that this is a breaking change, but I prefer to keep the config read-only instead of letting it as a dictionary.
If you are ok with that I will merge the branch this week.

**Comment by thoemmi** [comment]
I'm fine with that, I just wanted to make you aware of the issue.  I'm looking forward to the merge. 

Are you going to publish a new release and NuGet package once you've merged the changes?

**Comment by laedit** [comment]
I plan to make a new release in january, I won't have the time to do it until then and I'm waiting that the chocolatey packages are validated.

**Pull request merged**
