### PR TITLE
Fix site.title and page.id

### LINKED ISSUE #182: site.title is always null
I wanted to add a "title" variable in _config.yml and use it  as {{ site.title }} in a liquid template but it is always null.

The SiteContext class has a Title properties which override the "title" from _config.yml but there is no initialization of this property or am I missing something?

If not I will be happy to push a PR :smile:

### PR DESCRIPTION
**Pull request by laedit**
This should fix #182.
The site.title has been implemented like jekyll, but the page.id has some differences:
In Jekyll with the permalink /:categories/:year/:month/:day/:title/index.html the page id will be something like that: "/fr/2014/11/26/myfirstpost/myfirstpost".
In Pretzel it will be: "/fr/2014/11/26/myfirstpost/".
The other difference is that in Jekyll the pages have no id, only the posts have. In Pretzel both will have a generated id.

@shiftkey, @JakeGinnivan are you okay with that?

### CODE REVIEW

**Comment by shiftkey** [comment]
:thumbsup:

**Comment by laedit** [comment]
@shiftkey sorry to bother you, but is the TeamCity server working?
If not can I set an AppVeyor.com project for the Ci part?

**Comment by shiftkey** [comment]
Not sure, I'd have to ask @JakeGinnivan what's up.

If you want to take charge of the CI process, I'd highly recommend AppVeyor. I don't think Jake would mind either!

**Comment by JakeGinnivan** [comment]
Nope, happy for it to change.

I can also give you admin permission to the teamcity build if you want to modify that?

The biggest issue with the build is that when you release it doesn't upload the zip to github, it just pushes the chocolatey package which points to a zip which has not been uploaded

**Comment by JakeGinnivan** [comment]
Build is working - http://teamcity.ginnivan.net/viewType.html?buildTypeId=bt52

Report status to github is not setup though.

**Comment by JakeGinnivan** [comment]
@laedit just create an account and I will set you up

**Comment by laedit** [comment]
Done. And sorry about the failing test, I will fix it ASAP.

**Comment by JakeGinnivan** [comment]
@laedit done, you are project admin on the Pretzel project in teamcity.

If you need a hand setting anything up I am more than happy to help!

**Comment by laedit** [comment]
Weird, it seems that the GitHub repoart status plugin is well configured and activated but do nothing...
Could you update it to the latest version?
At least it supports the use of the GitHub personal access token, it will spare you to store you password.

**Comment by JakeGinnivan** [comment]
Will try to update it tonight.

**Comment by laedit** [comment]
The Team CIty server seems to not responding. Not a big problem, I have set up an AppVeyor project.

@shiftkey there is one little problem thought, the AppVeyor do not seem to add a build in the queue for each push, could you tell me if the "push" and "pull request" trigger are checked in the repo options?
Thanks.

**Comment by shiftkey** [comment]
> could you tell me if the "push" and "pull request" trigger are checked in the repo options?

I can only see "push" is configured - could you check the TeamCity settings and see if something is missing there?

**Comment by laedit** [comment]
Sorry, I wasn't clear, the Team CIty server is out.
But for AppVeyor, the configuration need to be done in the settings of the repo: could you check the "pull request" trigger for the AppVeyor webhook (https://ci.appveyor.com/api/github/webhook?id=rp8nq03r4b7mdecf)?
Thanks.

**Comment by shiftkey** [comment]
@laedit ok, I've added the webhook for the AppVeyor URL

**Comment by laedit** [comment]
@shiftkey Thanks! :smile:

**Pull request merged**
