### PR TITLE
This sassy commit is all the rage this summer.

### PR DESCRIPTION
**Pull request by vikingcode**
Solves #192 - introduces Sass for CSS generation. Uses Libsassnet to provide the Sassyness.

Switches out ILMerge for Fody/Costura. When handling unmanaged assemblies, this is the best solution. This required some modifications to how MEF was used.
It uses a very specific version of Fody/Costura because of issues with VS15, I think. Please don't update it.

### CODE REVIEW

**Comment by vikingcode** [comment]
This should probably also remove ilmerge.exe

**Comment by vikingcode** [comment]
This is also obviously not going to work with mono, since its a native binary for the Windahs Operatung Sostem. Is there any entirely MSIL version of Sass?

**Comment by kodfodrasz** [comment]
Even if it does not work on mono, it should be implemented that if this feature is not used on mono, other features are not affected.

IMHO it would also be nice if the user would be informed about this fact in an informative message instead of a cryptic stacktrace.

(I'm not an experienced DllImport user, so I don't know if this is true for the current state)

**Comment by laedit** [comment]
Thanks for the PR, it looks good.
There are just some changes to do:
 - remove all Fody/Costura, we will stop to merge pretzel (see #266)
 - is it possible to add some tests?

**Comment by vikingcode** [comment]
Just saw this. Nope nope and away!

**Pull request closed without merging**
