### PR TITLE
Run on Mono

### PR DESCRIPTION
**Pull request by thiagoabreu**
Hey guys. I recently read about this project and I was wondering if it runs on Mono.

I tried to run the .exe file and, joyfully, it worked. I mean, almost. It had some issues with the paths of the generated files but seems like all the libs were compatible. I saw you were working on it ( #215 ) and, as a Mono developer, I tried to figure out what was happening.

It was only a matter of fixing lower cases paths and using System.IO.Path instead of changing path strings. 

I compiled on VS 2015 RT (Windows 10) and tested in my Xubuntu machine with Mono 4.0. I'm able to run commands hungry (no big deal here), create, bake and taste, both with Razor and Liquid templates. It worked and was delicious.

I had problems running the automated tests, though. And didn't test the "import" command. I need some help with that.

Anyway, hope it's usefull. :D

### CODE REVIEW

**Comment by shiftkey** [comment]
@thiagoabreu this is amazing! Thanks for looking into this :heart::heart::heart::heart::heart:

There's some failing tests on this project - you can see the output [here](https://ci.appveyor.com/project/laedit/pretzel/build/0.2.1-PullRequest.253+178%20(Build%20182)) - have you had a chance to look into them?

**Comment by thiagoabreu** [comment]
I was having trouble with VS2015 skipping most of the tests. Thanks to AppVeyor I could find the failing tests.

Seems I "over fixed" the "MapToOutputPath" methods. It looks good now.

Have a taste:

captura de tela_2015-07-20_20-26-59

**Comment by shiftkey** [comment]
I'll let @laedit chime in here as he's been steering a bunch of this stuff recently.

Also cc @vikingcode as he was looking at Mono support earlier...

**Comment by thiagoabreu** [comment]
Found a bug in generating permalinks. Fixed now.

**Comment by thiagoabreu** [comment]
Fixing author (sorry, my bad)

**Comment by kodfodrasz** [comment]
I suspect some related code smell at https://github.com/Code52/pretzel/blob/master/src/Pretzel.Logic/Extensibility/Extensions/AzureHostSupport.cs#L46 and in line 52. I think the replacement target should be changed to PathSeparatorChar.

**Comment by thiagoabreu** [comment]
Agreed. The output is the same but the SeparatorChar makes clearer understanding.
Changed in other places too for consistency.

**Comment by thiagoabreu** [comment]
```
[00:00:17] The process cannot access the file 'C:\projects\pretzel\src\packages\DotlessClientOnly.1.4.1.0\DotlessClientOnly.1.4.1.0.nupkg' because it is being used by another process.
[00:00:17] Command exited with code 1
```
Hey, @shiftkey can you see what happened? :sweat_smile:

**Comment by laedit** [comment]
Sorry for the silence, I was out of town for a few weeks.
Thanks a lot for your hard work, I will review it as soon as I can, hopefully before the end of the week.

**Comment by laedit** [comment]
Sounds good to me, thanks again! :smiley: 
I just have two questions:
 - could you merge this branch with the updated master?
 - did you know any good ci platform for mono? Is Travis ok?

**Comment by thiagoabreu** [comment]
- could you merge this branch with the updated master?

Done.

- did you know any good ci platform for mono? Is Travis ok?

Travis is ok. The mono-project guys use Jenkins. The TeamCity also supports Mono. 

Just a reminder, my branch does not compile on Mono. The mono compiler reflection can't find all the Command tags, making Pretzel useless.

**Comment by laedit** [comment]
Thanks!
Just to be clear, right now to launch automatic tests on Linux we have to use the windows compilated Pretzel?
It can be complicated for testing, but I'll think at a solution.

**Comment by thiagoabreu** [comment]
Yes. Compile on Windows + .NET Framework, test on Unix + Mono.

That's one reason I didn't change the tests: I couldn't figure out how to set the mock file system to Unix style while at Windows. The other reason is I didn't want to brake the Windows implementation. :sweat_smile:

**Pull request merged**
