### PR TITLE
Better support for exclude config setting

### PR DESCRIPTION
**Pull request by dkarzon**
Allows the `exclude` config setting to be used as well as `pretzel > exclude` and adds support for folder excludes instead of only by full path.

### CODE REVIEW

**Comment by laedit** [comment]
Thanks for the PR!

Good point about the config setting, but instead of duplicating the setting I think we should only accept the same as Jekyll: `exclude`.
And please add or modify tests, we don't accept code that is not tested.

One more thing, is it possible that you update the `include` setting as well?

Thanks.

**Comment by dkarzon** [comment]
That sounds like a better option, I'll update and write some tests for the new structure and update the PR.

**Comment by dkarzon** [comment]
@laedit Not sure why my other commit hasn't come through to the PR but this has been done.

**Comment by laedit** [comment]
Great!
Is it possible to include a folder like you made possible to exclude one?

**Comment by laedit** [comment]
Excellent, thanks!

**Pull request merged**
